name: py build
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set py
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - name: dependencies py
        run: pip install -r 
          
      
