name: Send mail
on: push

jobs :
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: print Hello world
      run: echo "Hello World said by Ramya!!"

    
    - name: Send email
      uses: dawidd6/action-send-mail@v6
      with:
        server_address: smtp.gmail.com
        server_port: 465                 # or 465
        secure: true                     # encryption
        username: ${{ secrets.MAIL_USERNAME }}   # your full email (e.g., you@gmail.com)
        password: ${{ secrets.MAIL_PASSWORD }}   # Gmail App Password (NOT your normal password)
        from: "CI Bot <${{ secrets.MAIL_USERNAME }}>"
        to: "ramyalakshmi055@gmail.com"
        subject: "Build finished for ${{ github.repository }}"
        body: "Run #${{ github.run_number }} status: ${{ job.status }}"
    # Optional extras:
    # html_body: file://README.html
    # attachments: "dist/app.zip"
