name: Send mail
on: push

jobs :
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: print Hello world
      run: echo "Hello World said by Ramya!!"

    - name: Sending a mail
      if: $ {{ always() }}
      uses: devellany/send-mailer@v1.0.2
      with:
          host: smtp.google.com
          port: 465
          account: ${{ACCOUNT}}
          password: ${{MAIL_PASSWORD}}
          sender: devellany
          from: ${{secrets.MAIL_ADDRESS}}
          to: sharamanju16@gmail.com, ramyalakshmi055@gmail.com
          subject: mail title.
          body: your messages Hi dear, this is  a mail to user
            
          contentType: text/plain
            
          attachments: '[{"path":"README.md"}]' 
